name: Go Test Build and Deploy

on:
  push:
    branches:
      - main
 
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3

    - name: Set up Go
      uses: actions/setup-go@v3
      with:
        go-version: 1.21.0
       
    - name: Build
      run: go build -v -o tc main.go

    - uses: actions/upload-artifact@v3
      with:
          name: tc-artifact
          path: ./tc

  deploy:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - uses: actions/checkout@v3
      - uses: actions/download-artifact@v3
        with:
          name: tc-artifact
      - name: Deploy to server
        uses: appleboy/scp-action@master
        with:
           host: ${{ secrets.HOST }}
           username: ${{ secrets.USERNAME }}
           password: ${{ secrets.PASSWORD }}
           port: ${{ secrets.PORT }}
           source: ./tc
           target: "/home/${{ secrets.USERNAME }}/tc"

      - name: Start IIM Backend service and Reload Nginx
        uses: appleboy/ssh-action@master
        with:
           host: ${{ secrets.HOST }}
           username: ${{ secrets.USERNAME }}
           password: ${{ secrets.PASSWORD }}
           port: ${{ secrets.PORT }}
           script: |
               cd /home/${{ secrets.USERNAME }}/tc
               chmod +x tc
               echo ${{ secrets.PASSWORD }} | sudo -S systemctl stop tc.service 
               echo ${{ secrets.PASSWORD }} | sudo -S systemctl start tc.service 
               echo ${{ secrets.PASSWORD }} | sudo -S systemctl reload nginx

 
